name: Docker Build and Push

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: github.com/ChaitanyaSaiV/.github-workflows/docker-push.yml
    secrets: inherit
    with:
      ECR_REPOSITORY_NAME: ${{ github.event.repository.name }} # or a specific name if needed